# Generated by Django 4.0.4 on 2022-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='timetables',
        ),
        migrations.AddField(
            model_name='classes',
            name='timetables',
            field=models.ManyToManyField(to='api.timetable', verbose_name='Расписания'),
        ),
    ]
