# Generated by Django 4.0.4 on 2022-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_classes_timetables_classes_timetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonement',
            name='type_of_access',
        ),
        migrations.AddField(
            model_name='abonement',
            name='type_of_access',
            field=models.ManyToManyField(to='api.access', verbose_name='Доступы'),
        ),
    ]
